title: Arvin Manoj
logo: assets/ArvinManoj.png
# description: Results-driven professional with a PG Diploma in Embedded Systems Design and a B.E. in Electronics and Communication. Skilled in C, C++, Linux, Embedded Systems, and Robot Operating System. Proven collaborative and quick-learning abilities, with a competitive edge shown in hackathons and design contests. Eager to bring my technical expertise and passion for technology to a full-time role in the tech industry.
theme: jekyll-theme-minimal
